version: '3.8'

services:
  catstealer-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catstealer-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CatStealerDB;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true
      - CAAS__ApiKey=${CAAS_API_KEY}
      - FileStorage__BasePath=/app/CatImages
      - FileStorage__BaseUrl=http://localhost:5000
      - FileStorage__RequestPath=/StoredCatImages
    volumes:
      - cat_images:/app/CatImages
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - catstealer-network
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: catstealer-sqlserver
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${SA_PASSWORD}' -Q 'SELECT 1' -C || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - catstealer-network
    restart: unless-stopped

volumes:
  sqlserver_data:
  cat_images:

networks:
  catstealer-network:
    driver: bridge